import { Router } from "express";
import mongoose from "mongoose";
import multer from "multer";
import path from "node:path";
import { Area, AuditLog, BusinessSettings, CashSession, Coupon, Customer, Expense, InventoryMovement, Order, Product, ProductCategory, Sale, Table, User } from "../models.js";
import { asyncRoute, permit } from "../middleware.js";
import { audit, httpError, nextFolio } from "../utils.js";

const router = Router();
const elevated = (user) => user.isInitialAdmin || ["superadministrador", "admin"].includes(user.role) || user.permissions.includes("*");
const manageUsers = (req, res, next) => elevated(req.user) || req.user.permissions.includes("usuarios.administrar") ? next() : res.status(403).json({ message: "No tienes permiso para administrar usuarios" });
const can = (req, permission) => elevated(req.user) || req.user.permissions.includes(permission);
export const availablePermissions = [
  ["usuarios.administrar", "Administrar usuarios, roles y permisos"],
  ["modulo.dashboard", "Módulo: Resumen"], ["modulo.mesas", "Módulo: Mesas y áreas"], ["modulo.meseros", "Módulo: Meseros"],
  ["modulo.ventas", "Módulo: Punto de venta"], ["modulo.comandas", "Módulo: Comandas"], ["modulo.productos", "Módulo: Productos y categorías"],
  ["modulo.inventario", "Módulo: Inventario"], ["modulo.caja", "Módulo: Caja"], ["modulo.clientes", "Módulo: Clientes"],
  ["modulo.cupones", "Módulo: Cupones"], ["modulo.gastos", "Módulo: Gastos"], ["modulo.reportes", "Módulo: Reportes"],
  ["modulo.auditoria", "Módulo: Auditoría"], ["modulo.configuracion", "Módulo: Configuración"],
  ["productos.agregar", "Crear productos"], ["productos.editar", "Editar productos"], ["productos.eliminar", "Eliminar productos"],
  ["categorias.administrar", "Administrar categorías de comida"],
  ["inventario.editar", "Entradas y salidas"], ["inventario.ver_historial", "Historial de inventario"],
  ["mesas.agregar", "Crear mesas y áreas"], ["mesas.editar", "Editar mesas"], ["mesas.eliminar", "Eliminar mesas"], ["mesas.todas", "Usar todas las mesas"],
  ["meseros.administrar", "Crear meseros y asignar mesas"],
  ["comandas.agregar", "Crear comandas"], ["comandas.actualizar", "Actualizar cocina"], ["comandas.cancelar", "Cancelar comandas"], ["comandas.chat", "Chat de cocina"],
  ["ventas.agregar", "Registrar ventas"], ["ventas.credito", "Venta a crédito"], ["ventas.cortesia", "Cortesías"], ["ventas.descuento", "Descuento manual"], ["ventas.cupon", "Aplicar cupones"], ["ventas.costo", "Venta a costo"], ["ventas.mayoreo", "Venta mayoreo"], ["ventas.editar", "Editar ventas"], ["ventas.cancelar", "Cancelar ventas"],
  ["caja.abrir", "Abrir caja"], ["caja.movimientos", "Movimientos de caja"], ["caja.cerrar", "Cerrar caja"],
  ["clientes.agregar", "Crear clientes"], ["clientes.editar", "Editar clientes"], ["clientes.ver_identidad", "Ver INE"], ["clientes.verificar_identidad", "Cargar INE"], ["creditos.abonar", "Registrar abonos"],
  ["cupones.agregar", "Crear cupones"], ["cupones.editar", "Editar cupones"], ["gastos.agregar", "Registrar gastos"],
  ["reportes.ver", "Ver reportes"], ["reportes.descargar", "Descargar PDF"], ["auditoria.ver", "Ver auditoría"], ["configuracion.editar", "Editar configuración"],
];
const rolePermissions = {
  superadministrador: ["*"], admin: ["*"],
  supervisor: ["modulo.dashboard", "modulo.mesas", "modulo.meseros", "modulo.ventas", "modulo.comandas", "modulo.productos", "modulo.inventario", "modulo.caja", "modulo.clientes", "modulo.cupones", "modulo.gastos", "modulo.reportes", "modulo.auditoria", "mesas.agregar", "mesas.editar", "mesas.eliminar", "mesas.todas", "meseros.administrar", "comandas.agregar", "comandas.actualizar", "comandas.cancelar", "comandas.chat", "ventas.agregar", "ventas.credito", "ventas.descuento", "ventas.cupon", "productos.agregar", "productos.editar", "categorias.administrar", "inventario.editar", "inventario.ver_historial", "caja.abrir", "caja.movimientos", "caja.cerrar", "clientes.agregar", "clientes.editar", "creditos.abonar", "reportes.ver", "reportes.descargar", "auditoria.ver"],
  caja: ["modulo.meseros", "modulo.ventas", "modulo.comandas", "modulo.productos", "modulo.inventario", "modulo.caja", "ventas.agregar", "ventas.credito", "creditos.abonar", "comandas.agregar", "comandas.actualizar", "inventario.ver_historial", "caja.abrir", "caja.movimientos", "caja.cerrar", "mesas.todas"],
  mesero: ["modulo.ventas", "modulo.comandas", "modulo.inventario", "comandas.agregar", "comandas.chat", "ventas.agregar", "inventario.ver_historial"],
  barra: ["modulo.comandas", "modulo.meseros", "modulo.productos", "modulo.inventario", "comandas.actualizar", "comandas.chat", "inventario.ver_historial"],
  capitan: ["modulo.mesas", "modulo.meseros", "modulo.ventas", "modulo.comandas", "modulo.inventario", "mesas.editar", "mesas.todas", "meseros.administrar", "comandas.agregar", "comandas.actualizar", "comandas.chat", "ventas.agregar", "inventario.ver_historial"],
  cocina: ["modulo.comandas", "comandas.actualizar", "comandas.chat"], reparto: ["modulo.comandas", "comandas.actualizar", "comandas.chat"],
};
const userPayload = (body) => { const payload = {}; for (const field of ["name", "username", "email", "role", "permissions", "active"]) if (body[field] !== undefined) payload[field] = body[field]; return payload; };
const imageStorage = (folder) => multer.diskStorage({ destination: folder, filename: (_req, file, callback) => callback(null, `${Date.now()}-${Math.random().toString(36).slice(2)}${path.extname(file.originalname).toLowerCase()}`) });
const imageFilter = (_req, file, callback) => callback(null, ["image/jpeg", "image/png", "image/webp"].includes(file.mimetype));
const productUpload = multer({ storage: imageStorage("uploads/products"), limits: { fileSize: 5 * 1024 * 1024 }, fileFilter: imageFilter });
const identityUpload = multer({ storage: imageStorage("uploads/private/identity"), limits: { fileSize: 5 * 1024 * 1024 }, fileFilter: imageFilter });
const profileUpload = multer({ storage: imageStorage("uploads/profiles"), limits: { fileSize: 5 * 1024 * 1024 }, fileFilter: imageFilter });
const parseData = (req) => typeof req.body.data === "string" ? JSON.parse(req.body.data) : req.body;

router.get("/products", asyncRoute(async (req, res) => {
  const filter = { active: req.query.includeInactive === "true" ? { $in: [true, false] } : true };
  if (req.query.search) { const pattern = new RegExp(String(req.query.search).replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i"); filter.$or = [{ name: pattern }, { code: pattern }, { category: pattern }]; }
  res.json(await Product.find(filter).sort({ category: 1, name: 1 }).lean());
}));
router.post("/products", permit("productos.agregar"), productUpload.single("image"), asyncRoute(async (req, res) => {
  const payload = parseData(req); if (req.file) payload.imageUrl = `/uploads/products/${req.file.filename}`; const product = await Product.create(payload);
  if (product.stock) await InventoryMovement.create({ product: product._id, type: "entrada", quantity: product.stock, stockBefore: 0, stockAfter: product.stock, reason: "Existencia inicial", user: req.user._id });
  await audit(req, { action: "Creó producto", module: "Productos", entity: "Product", entityId: product._id, reference: product.code, metadata: { code: product.code } }); res.status(201).json(product);
}));
router.patch("/products/:id", permit("productos.editar"), productUpload.single("image"), asyncRoute(async (req, res) => {
  const payload = parseData(req); if (req.file) payload.imageUrl = `/uploads/products/${req.file.filename}`; const before = await Product.findById(req.params.id); if (!before) throw httpError(404, "Producto no encontrado");
  if (payload.stock !== undefined && Number(payload.stock) !== before.stock) { const stockAfter = Number(payload.stock); await InventoryMovement.create({ product: before._id, type: "ajuste", quantity: stockAfter - before.stock, stockBefore: before.stock, stockAfter, reason: payload.stockReason || "Ajuste desde edición de producto", user: req.user._id }); }
  delete payload.stockReason; const product = await Product.findByIdAndUpdate(req.params.id, payload, { new: true, runValidators: true });
  await audit(req, { action: "Actualizó producto", module: "Productos", entity: "Product", entityId: product._id, reference: product.code, metadata: { blocked86: product.stock === 86 } }); res.json(product);
}));
router.delete("/products/:id", permit("productos.eliminar"), asyncRoute(async (req, res) => { const product = await Product.findByIdAndUpdate(req.params.id, { active: false, available: false }, { new: true }); if (!product) throw httpError(404, "Producto no encontrado"); await audit(req, { action: "Eliminó producto", module: "Productos", entity: "Product", entityId: product._id, reference: product.code, metadata: { code: product.code } }); res.status(204).end(); }));

router.get("/product-categories", asyncRoute(async (_req, res) => { const legacyNames = (await Product.distinct("category", { active: true })).filter(Boolean); if (legacyNames.length) await Promise.all(legacyNames.map((name) => ProductCategory.updateOne({ name }, { $setOnInsert: { name, active: true } }, { upsert: true }))); res.json(await ProductCategory.find({ active: true }).sort({ name: 1 }).lean()); }));
router.post("/product-categories", permit("categorias.administrar"), asyncRoute(async (req, res) => { const category = await ProductCategory.create({ name: req.body.name, description: req.body.description, color: req.body.color }); await audit(req, { action: "Creó categoría de comida", module: "Categorías", entity: "ProductCategory", entityId: category._id, reference: category.name }); res.status(201).json(category); }));
router.patch("/product-categories/:id", permit("categorias.administrar"), asyncRoute(async (req, res) => { const category = await ProductCategory.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true }); if (!category) throw httpError(404, "Categoría no encontrada"); await audit(req, { action: "Actualizó categoría de comida", module: "Categorías", entity: "ProductCategory", entityId: category._id, reference: category.name }); res.json(category); }));
router.delete("/product-categories/:id", permit("categorias.administrar"), asyncRoute(async (req, res) => { const category = await ProductCategory.findById(req.params.id); if (!category) throw httpError(404, "Categoría no encontrada"); if (await Product.exists({ category: category.name, active: true })) throw httpError(409, "La categoría tiene productos activos"); await ProductCategory.deleteOne({ _id: category._id }); await audit(req, { action: "Eliminó categoría de comida", module: "Categorías", entity: "ProductCategory", entityId: category._id, reference: category.name }); res.status(204).end(); }));

router.get("/inventory/movements", permit("inventario.ver_historial", "inventario.editar"), asyncRoute(async (req, res) => { const filter = req.query.product ? { product: req.query.product } : {}; res.json(await InventoryMovement.find(filter).populate("product", "code name unit").populate("order", "folio").populate("sale", "folio").populate("user", "name username").sort({ createdAt: -1 }).limit(Math.min(Number(req.query.limit) || 500, 1000))); }));
router.post("/products/:id/stock", permit("inventario.editar"), asyncRoute(async (req, res) => {
  const raw = Number(req.body.quantity); if (!Number.isFinite(raw) || raw === 0) throw httpError(422, "La cantidad debe ser distinta de cero");
  const direction = req.body.direction || (raw > 0 ? "entrada" : "salida"); const quantity = direction === "entrada" ? Math.abs(raw) : -Math.abs(raw); const movementType = req.body.type === "cortesia" ? "cortesia" : direction;
  if (movementType === "cortesia" && !can(req, "ventas.cortesia")) throw httpError(403, "Sólo un usuario autorizado puede registrar cortesías");
  const before = await Product.findById(req.params.id); if (!before || before.stock + quantity < 0) throw httpError(409, "Producto inexistente o stock insuficiente");
  const product = await Product.findByIdAndUpdate(req.params.id, { $inc: { stock: quantity } }, { new: true, runValidators: true });
  await InventoryMovement.create({ product: product._id, type: movementType, quantity, stockBefore: before.stock, stockAfter: product.stock, reason: String(req.body.reason || "Movimiento manual"), user: req.user._id });
  await audit(req, { action: quantity > 0 ? "Entrada de inventario" : movementType === "cortesia" ? "Salida por cortesía" : "Salida de inventario", module: "Inventario", entity: "Product", entityId: product._id, reference: product.code, metadata: { code: product.code, quantity, reason: req.body.reason, stockAfter: product.stock } }); res.json(product);
}));

router.get("/customers", asyncRoute(async (req, res) => { const search = String(req.query.search ?? "").trim(); const pattern = search ? new RegExp(search.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i") : null; const filter = pattern ? { active: true, $or: [{ name: pattern }, { phone: pattern }, { email: pattern }] } : { active: true }; res.json(await Customer.find(filter).sort({ name: 1 }).limit(500)); }));
router.post("/customers", permit("clientes.agregar"), identityUpload.single("ine"), asyncRoute(async (req, res) => { const payload = parseData(req); if (req.file) { payload.ineImageUrl = req.file.path; payload.birthdayVerifiedAt = payload.birthDate ? new Date() : undefined; } const customer = await Customer.create(payload); await audit(req, { action: "Creó cliente", module: "Clientes", entity: "Customer", entityId: customer._id, metadata: { ine: Boolean(req.file) } }); res.status(201).json(customer); }));
router.patch("/customers/:id", permit("clientes.editar"), asyncRoute(async (req, res) => { const customer = await Customer.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true }); if (!customer) throw httpError(404, "Cliente no encontrado"); await audit(req, { action: "Actualizó cliente", module: "Clientes", entity: "Customer", entityId: customer._id }); res.json(customer); }));
router.get("/customers/:id/debts", asyncRoute(async (req, res) => res.json(await Sale.find({ customer: req.params.id, paymentCondition: "credito", status: "completada", balanceDue: { $gt: 0 } }).populate("order", "folio orderType table items").sort({ dueDate: 1, createdAt: 1 }))));
router.post("/customers/:id/identity", permit("clientes.verificar_identidad"), identityUpload.single("ine"), asyncRoute(async (req, res) => { if (!req.file) throw httpError(422, "Selecciona una imagen de INE"); const update = { ineImageUrl: req.file.path, birthdayVerifiedAt: new Date() }; if (req.body.birthDate) update.birthDate = new Date(req.body.birthDate); const customer = await Customer.findByIdAndUpdate(req.params.id, update, { new: true, runValidators: true }); if (!customer) throw httpError(404, "Cliente no encontrado"); await audit(req, { action: "Verificó identidad", module: "Clientes", entity: "Customer", entityId: customer._id }); res.json({ id: customer._id, birthDate: customer.birthDate, birthdayVerifiedAt: customer.birthdayVerifiedAt }); }));
router.get("/customers/:id/identity", permit("clientes.ver_identidad"), asyncRoute(async (req, res) => { const customer = await Customer.findById(req.params.id).select("ineImageUrl"); if (!customer?.ineImageUrl) throw httpError(404, "INE no registrada"); res.sendFile(path.resolve(customer.ineImageUrl)); }));

router.get("/permissions", manageUsers, asyncRoute(async (_req, res) => res.json(availablePermissions.map(([id, label]) => ({ id, label })))));
router.get("/roles", manageUsers, asyncRoute(async (_req, res) => res.json(Object.entries(rolePermissions).filter(([role]) => !["cocina", "reparto"].includes(role)).map(([id, permissions]) => ({ id, label: ({ superadministrador: "Superadministrador", admin: "Administrador", supervisor: "Supervisor", caja: "Cajero", mesero: "Mesero", barra: "Encargado de barra", capitan: "Capitán de meseros" })[id] || id, permissions })))));
router.get("/users", manageUsers, asyncRoute(async (req, res) => { const filter = req.query.role ? { role: req.query.role } : {}; res.json(await User.find(filter).select("name username email role permissions active isInitialAdmin profileImageUrl createdAt").sort({ name: 1 })); }));
router.post("/users", manageUsers, asyncRoute(async (req, res) => { const payload = userPayload(req.body); const password = String(req.body.password || ""); if (password.length < 12) throw httpError(422, "La contraseña debe tener al menos 12 caracteres"); if (payload.role === "superadministrador" && !req.user.isInitialAdmin && req.user.role !== "superadministrador") throw httpError(403, "Sólo el superadministrador puede crear otro superadministrador"); if (!Array.isArray(payload.permissions) || payload.permissions.length === 0) payload.permissions = rolePermissions[payload.role] ?? []; const user = await User.create({ ...payload, passwordHash: await User.hashPassword(password), isInitialAdmin: false, passwordChangedAt: new Date() }); await audit(req, { action: "Creó usuario", module: "Usuarios", entity: "User", entityId: user._id, reference: user.username, metadata: { role: user.role, permissions: user.permissions } }); res.status(201).json({ id: user._id, name: user.name, username: user.username, role: user.role, permissions: user.permissions, active: user.active }); }));
router.patch("/users/:id", manageUsers, asyncRoute(async (req, res) => { const target = await User.findById(req.params.id); if (!target) throw httpError(404, "Usuario no encontrado"); if ((target.role === "superadministrador" || target.isInitialAdmin || req.body.role === "superadministrador") && !req.user.isInitialAdmin && req.user.role !== "superadministrador") throw httpError(403, "Sólo el superadministrador puede modificar este usuario"); const payload = userPayload(req.body); const password = String(req.body.password || ""); if (password) { if (password.length < 12) throw httpError(422, "La contraseña debe tener al menos 12 caracteres"); payload.passwordHash = await User.hashPassword(password); payload.passwordChangedAt = new Date(); } const user = await User.findByIdAndUpdate(req.params.id, payload, { new: true, runValidators: true }).select("name username email role permissions active profileImageUrl"); await audit(req, { action: "Actualizó usuario", module: "Usuarios", entity: "User", entityId: user._id, reference: user.username, metadata: { role: user.role, permissions: user.permissions } }); res.json(user); }));
router.post("/users/:id/profile-image", profileUpload.single("image"), asyncRoute(async (req, res) => { if (String(req.user._id) !== req.params.id && !req.user.isInitialAdmin) throw httpError(403, "No puedes cambiar la imagen de otro usuario"); if (!req.file) throw httpError(422, "Selecciona una imagen"); const user = await User.findByIdAndUpdate(req.params.id, { profileImageUrl: `/uploads/profiles/${req.file.filename}` }, { new: true }).select("name username profileImageUrl"); await audit(req, { action: "Actualizó imagen de perfil", module: "Usuarios", entity: "User", entityId: user._id }); res.json(user); }));
router.post("/users/me/password", asyncRoute(async (req, res) => { const { currentPassword, newPassword } = req.body; const user = await User.findById(req.user._id).select("+passwordHash"); if (!(await user.verifyPassword(currentPassword))) throw httpError(401, "La contraseña actual es incorrecta"); if (!newPassword || newPassword.length < 12) throw httpError(422, "La contraseña nueva debe tener al menos 12 caracteres"); user.passwordHash = await User.hashPassword(newPassword); user.passwordChangedAt = new Date(); await user.save(); await audit(req, { action: "Actualizó contraseña", module: "Configuración", entity: "User", entityId: user._id }); res.status(204).end(); }));

router.get("/waiters", asyncRoute(async (_req, res) => {
  const [waiters, tables] = await Promise.all([
    User.find({ role: "mesero", active: true }).select("name username email permissions active profileImageUrl createdAt").sort({ name: 1 }).lean(),
    Table.find({ active: true }).select("number label name area accessMode assignedWaiters status currentOrder").populate("currentOrder", "folio commandStatus total serviceSource assignedWaiter createdBy").sort({ area: 1, label: 1, number: 1 }).lean(),
  ]);
  res.json(waiters.map((waiter) => ({ ...waiter, assignedTables: tables.filter((table) => table.assignedWaiters.some((id) => String(id) === String(waiter._id))) })));
}));
router.post("/waiters", manageUsers, asyncRoute(async (req, res) => {
  const password = String(req.body.password || "");
  if (password.length < 12) throw httpError(422, "La contraseña temporal debe tener al menos 12 caracteres");
  const user = await User.create({ name: req.body.name, username: req.body.username, email: req.body.email || undefined, role: "mesero", permissions: Array.isArray(req.body.permissions) && req.body.permissions.length ? req.body.permissions : rolePermissions.mesero, passwordHash: await User.hashPassword(password), isInitialAdmin: false, passwordChangedAt: new Date() });
  await audit(req, { action: "Creó mesero", module: "Meseros", entity: "User", entityId: user._id, metadata: { username: user.username } });
  res.status(201).json({ id: user._id, name: user.name, username: user.username, role: user.role, permissions: user.permissions, assignedTables: [] });
}));
router.get("/bar-users", asyncRoute(async (_req, res) => res.json(await User.find({ role: "barra", active: true }).select("name username profileImageUrl role permissions").sort({ name: 1 }).lean())));
router.patch("/waiters/:id/assignments", permit("meseros.administrar"), asyncRoute(async (req, res) => {
  const waiter = await User.findOne({ _id: req.params.id, role: "mesero", active: true });
  if (!waiter) throw httpError(404, "Mesero no encontrado");
  const tableIds = [...new Set((Array.isArray(req.body.tableIds) ? req.body.tableIds : []).map(String))];
  if (tableIds.some((id) => !mongoose.isValidObjectId(id))) throw httpError(422, "Una mesa seleccionada no es válida");
  const matchingTables = await Table.countDocuments({ _id: { $in: tableIds }, active: true });
  if (matchingTables !== tableIds.length) throw httpError(422, "Una o más mesas no existen o están inactivas");
  await Table.updateMany({ assignedWaiters: waiter._id }, { $pull: { assignedWaiters: waiter._id } });
  if (tableIds.length) await Table.updateMany({ _id: { $in: tableIds } }, { $addToSet: { assignedWaiters: waiter._id }, $set: { accessMode: "restringida" } });
  const assignedTables = await Table.find({ assignedWaiters: waiter._id, active: true }).select("number label name area accessMode status currentOrder").populate("currentOrder", "folio commandStatus total serviceSource assignedWaiter createdBy").sort({ area: 1, label: 1, number: 1 }).lean();
  await audit(req, { action: "Asignó mesas a mesero", module: "Meseros", entity: "User", entityId: waiter._id, metadata: { tableIds } });
  res.json({ id: waiter._id, name: waiter.name, username: waiter.username, role: waiter.role, permissions: waiter.permissions, assignedTables });
}));

router.get("/areas", asyncRoute(async (_req, res) => res.json(await Area.find({ active: true }).sort({ name: 1 }))));
router.post("/areas", permit("mesas.agregar"), asyncRoute(async (req, res) => { const area = await Area.create(req.body); await audit(req, { action: "Creó área", module: "Mesas", entity: "Area", entityId: area._id }); res.status(201).json(area); }));
router.patch("/areas/:id", permit("mesas.editar"), asyncRoute(async (req, res) => { const area = await Area.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true }); if (!area) throw httpError(404, "Área no encontrada"); await audit(req, { action: "Actualizó área", module: "Mesas", entity: "Area", entityId: area._id }); res.json(area); }));
router.delete("/areas/:id", permit("mesas.editar"), asyncRoute(async (req, res) => { if (await Table.exists({ areaRef: req.params.id, active: true })) throw httpError(409, "El área tiene mesas activas"); const area = await Area.findByIdAndUpdate(req.params.id, { active: false }, { new: true }); if (!area) throw httpError(404, "Área no encontrada"); await audit(req, { action: "Eliminó área", module: "Mesas", entity: "Area", entityId: area._id }); res.status(204).end(); }));

router.get("/tables", asyncRoute(async (req, res) => { const missingLabels = await Table.find({ active: true, $or: [{ label: { $exists: false } }, { label: null }, { label: "" }] }); for (const table of missingLabels) { table.label = String(table.name || `MESA ${table.number}`).toUpperCase(); await table.save(); } const filter = { active: true }; if (!can(req, "mesas.todas")) filter.$or = [{ accessMode: "libre" }, { assignedWaiters: req.user._id }, { assignedWaiters: { $size: 0 } }]; res.json(await Table.find(filter).populate("areaRef", "name color").populate("assignedWaiters", "name username profileImageUrl role").populate("customer", "name birthDate birthdayVerifiedAt creditBalance").populate({ path: "currentOrder", select: "folio total commandStatus items messages estimatedMinutes timerEndsAt createdAt paymentCondition serviceSource assignedWaiter assignedBar waiter createdBy", populate: [{ path: "messages.user", select: "name profileImageUrl" }, { path: "assignedWaiter", select: "name username profileImageUrl" }, { path: "assignedBar", select: "name username profileImageUrl" }, { path: "waiter", select: "name username profileImageUrl" }, { path: "createdBy", select: "name username profileImageUrl" }] }).sort({ area: 1, label: 1, number: 1 })); }));
router.post("/tables", permit("mesas.agregar"), asyncRoute(async (req, res) => {
  const payload = { ...req.body };
  const label = String(payload.label || payload.name || "").trim().toUpperCase(); if (!label) throw httpError(422, "Escribe el identificador de la mesa, por ejemplo A1 o MESA 1"); payload.label = label; payload.name = label;
  if (await Table.exists({ label, active: true })) throw httpError(409, `Ya existe la mesa ${label}`);
  if (!payload.areaRef) throw httpError(422, "Selecciona el área de la mesa");
  if (payload.areaRef) { const area = await Area.findById(payload.areaRef); if (!area) throw httpError(422, "Área no válida"); payload.area = area.name; }
  const waiterIds = Array.isArray(payload.assignedWaiters) ? payload.assignedWaiters : [];
  if (await User.countDocuments({ _id: { $in: waiterIds }, role: "mesero", active: true }) !== waiterIds.length) throw httpError(422, "Uno de los meseros seleccionados no es válido");
  payload.accessMode = payload.accessMode === "restringida" ? "restringida" : "libre"; if (payload.accessMode === "restringida" && !waiterIds.length) throw httpError(422, "Una mesa restringida necesita un mesero asignado");
  const highest = await Table.findOne().sort({ number: -1 }).select("number").lean(); payload.number = Math.max(Number(highest?.number || 0) + 1, 1); payload.status = "libre"; payload.customer = null; payload.guestName = null; payload.guestCount = 0; payload.arrivedAt = null; payload.currentOrder = null;
  const table = await Table.create(payload); await audit(req, { action: "Registró mesa", module: "Mesas", entity: "Table", entityId: table._id, reference: table.label, metadata: { area: table.area, accessMode: table.accessMode, assignedWaiters: table.assignedWaiters } }); res.status(201).json(table);
}));
router.patch("/tables/:id", permit("mesas.editar"), asyncRoute(async (req, res) => { const payload = { ...req.body }; if (payload.label) { payload.label = String(payload.label).trim().toUpperCase(); payload.name = payload.label; if (await Table.exists({ _id: { $ne: req.params.id }, label: payload.label, active: true })) throw httpError(409, `Ya existe la mesa ${payload.label}`); } if (payload.areaRef) { const area = await Area.findById(payload.areaRef); if (area) payload.area = area.name; } const table = await Table.findByIdAndUpdate(req.params.id, payload, { new: true, runValidators: true }); if (!table) throw httpError(404, "Mesa no encontrada"); await audit(req, { action: "Actualizó mesa", module: "Mesas", entity: "Table", entityId: table._id, reference: table.label, metadata: { status: table.status, assignedWaiters: table.assignedWaiters } }); res.json(table); }));
router.delete("/tables/:id", permit("mesas.eliminar"), asyncRoute(async (req, res) => { const table = await Table.findById(req.params.id); if (!table) throw httpError(404, "Mesa no encontrada"); if (table.currentOrder) throw httpError(409, "No puedes eliminar una mesa con una comanda abierta"); await audit(req, { action: "Eliminó mesa", module: "Mesas", entity: "Table", entityId: table._id, reference: table.label || table.name || String(table.number), metadata: { area: table.area } }); await Table.deleteOne({ _id: table._id }); res.status(204).end(); }));

router.get("/coupons", asyncRoute(async (_req, res) => res.json(await Coupon.find().sort({ active: -1, endsAt: 1 }))));
router.post("/coupons", permit("cupones.agregar"), asyncRoute(async (req, res) => { const coupon = await Coupon.create(req.body); await audit(req, { action: "Creó cupón", module: "Cupones", entity: "Coupon", entityId: coupon._id }); res.status(201).json(coupon); }));
router.patch("/coupons/:id", permit("cupones.editar"), asyncRoute(async (req, res) => { const coupon = await Coupon.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true }); if (!coupon) throw httpError(404, "Cupón no encontrado"); await audit(req, { action: "Actualizó cupón", module: "Cupones", entity: "Coupon", entityId: coupon._id }); res.json(coupon); }));

router.get("/expenses", asyncRoute(async (req, res) => res.json(await Expense.find().populate("user", "name username").sort({ occurredAt: -1 }).limit(Number(req.query.limit) || 500))));
router.post("/expenses", permit("gastos.agregar"), asyncRoute(async (req, res) => { const session = await mongoose.startSession(); try { const expense = await session.withTransaction(async () => { const amount = Number(req.body.amount); if (!Number.isFinite(amount) || amount <= 0) throw httpError(422, "El monto del gasto no es válido"); const cash = await CashSession.findOne({ status: "abierta" }).sort({ openedAt: -1 }).session(session); if (req.body.paymentMethod === "efectivo" && !cash) throw httpError(409, "Debe existir una caja abierta para registrar un gasto en efectivo"); const folio = await nextFolio("expenses", "GASTO", 6, session); const [created] = await Expense.create([{ ...req.body, amount, folio, user: req.user._id, cashSession: cash?._id ?? null }], { session }); if (cash) { cash.movements.push({ type: "gasto", amount: -amount, method: req.body.paymentMethod, reason: `${folio} · ${req.body.concept}`, reference: created._id, user: req.user._id }); await cash.save({ session }); } await audit(req, { action: "Registró gasto", module: "Gastos", entity: "Expense", entityId: created._id, reference: folio, metadata: { amount, paymentMethod: req.body.paymentMethod } }, session); return created; }); res.status(201).json(expense); } finally { await session.endSession(); } }));

router.get("/settings/business", asyncRoute(async (_req, res) => res.json(await BusinessSettings.findOneAndUpdate({ key: "main" }, { $set: { systemVersion: "6.1.2" }, $setOnInsert: { key: "main" } }, { new: true, upsert: true, setDefaultsOnInsert: true }))));
router.patch("/settings/business", permit("configuracion.editar"), asyncRoute(async (req, res) => { const allowed = {}; for (const field of ["businessName", "legalName", "taxId", "address", "phone", "email", "ticketFooter", "ticketSize", "theme", "accentColor", "soundEnabled", "loginTitle", "loginSubtitle", "loginBackgroundUrl", "slogan", "socialNetworks"]) if (req.body[field] !== undefined) allowed[field] = req.body[field]; const settings = await BusinessSettings.findOneAndUpdate({ key: "main" }, { $set: allowed, $setOnInsert: { key: "main" } }, { new: true, upsert: true, runValidators: true, setDefaultsOnInsert: true }); await audit(req, { action: "Actualizó panel de control del servidor", module: "Configuración", entity: "BusinessSettings", entityId: settings._id, metadata: Object.keys(allowed) }); res.json(settings); }));
router.get("/audit", permit("auditoria.ver"), asyncRoute(async (req, res) => { const filter = req.query.module ? { module: req.query.module } : {}; const entries = await AuditLog.find(filter).populate("user", "name username profileImageUrl").sort({ createdAt: -1 }).limit(Math.min(Number(req.query.limit) || 500, 1000)).lean(); res.json(entries.map((entry) => ({ ...entry, reference: entry.reference || entry.metadata?.folio || entry.metadata?.code || entry.metadata?.username || "Sin referencia" }))); }));

export default router;
